baseURL = "https://www.kompound.solutions/"
languageCode = "en-us"
title = "Kompound Solutions"
theme = "kompound"

defaultContentLanguage = "en"

[outputs]
  home = ["HTML", "JSON"]

[languages]
  [languages.en]
  weight = 0
  languageName = "English"
    [[languages.en.menu.header]]
      weight = 1
      name = "Home"
      url = "/"
    [[languages.en.menu.header]]
      weight = 6
      name = "Developer corner"
      url = "/blog/"
    [[languages.en.menu.header]]
      weight = 3
      name = "Service"
      url = "/service/"
    [[languages.en.menu.header]]
      weight = 5
      name = "Contact"
      url = "/contact/"
    [[languages.en.menu.legal]]
      weight = 1
      name = "Contact us"
      url = "/contact/"
    [[languages.en.menu.legal]]
      weight = 2
      name = "Subject access request (GDPR)"
      url = "/sar/"
      pre = "Request your saved data as regulated by the General Data Protection Regulation"
    [[languages.en.menu.legal]]
      weight = 4
      name = "Privacy Policy"
      url = "/privacy/"
    [[languages.en.menu.legal]]
      weight = 5
      name = "Imprint"
      url = "/impressum/"
    [[languages.en.menu.legal]]
      weight = 6
      name = "© 2018 Kompound solutions"
    [[languages.en.menu.quicklinks]]
      name = "Request a quote"
      url = "/quote/"
    [[languages.en.menu.quicklinks]]
      name = "Partners"
      url = "/partners/"
    [[languages.en.menu.quicklinks]]
      name = "Frequently Asked Questions"
      url = "/faq/"

    [[languages.en.menu.ourservices]]
      name = "Paperless office"
      weight = 1
      url = "/services/#demo1"
    [[languages.en.menu.ourservices]]
      name = "Human resource planing and team communication"
      weight = 2
      url = "/services/#demo1"
    [[languages.en.menu.ourservices]]
      name = "Automation and Smart Control"
      weight = 3
      url = "/services/#demo2"
    [[languages.en.menu.ourservices]]
      name = "IoT Device design and integration"
      weight = 4
      url = "/services/#demo3"

  [languages.de]
  weight = 10
  languageName = "Deutsch"
    [[languages.de.menu.header]]
      weight = 1
      name = "Startseite"
      url = "/"
    [[languages.de.menu.header]]
      weight = 6
      name = "Developer corner"
      url = "/blog/"
    [[languages.de.menu.header]]
      weight = 3
      name = "Services"
      url = "/service/"
    [[languages.de.menu.header]]
      weight = 5
      name = "Kontakt"
      url = "/contact/"
    [[languages.de.menu.legal]]
      weight = 1
      name = "Kontakt"
      url = "/contact/"
    [[languages.de.menu.legal]]
      weight = 2
      name = "Auskunftsersuch (DSGVO)"
      url = "/sar/"
      pre = "Eigene Daten anfordern, entsprechend wie in der EU-Datenschutz-Grundverordnung vorgeschrieben"
    [[languages.de.menu.legal]]
      weight = 4
      name = "Datenschutzerklärung"
      url = "/privacy/"
    [[languages.de.menu.legal]]
      weight = 5
      name = "Impressum"
      url = "/impressum/"
    [[languages.de.menu.legal]]
      weight = 6
      name = "© 2018 Kompound solutions"
    [[languages.de.menu.quicklinks]]
      name = "Kostenvoranschlag"
      url = "/quote/"
    [[languages.de.menu.quicklinks]]
      name = "Partner"
      url = "/partners/"
    [[languages.de.menu.quicklinks]]
      name = "Häufig gestellte Fragen"
      url = "/faq/"

    [[languages.de.menu.ourservices]]
      name = "Papierloses Büro"
      weight = 1
      url = "/services/#demo1"
    [[languages.de.menu.ourservices]]
      name = "Intelligente Arbeitsplanung und Team Kollaboration"
      weight = 2
      url = "/services/#demo1"
    [[languages.de.menu.ourservices]]
      name = "Automatisierung und Smarte Systemkontrolle"
      weight = 3
      url = "/services/#demo2"
    [[languages.de.menu.ourservices]]
      name = "IoT Geräte Entwicklung und Einbindung"
      weight = 4
      url = "/services/#demo3"

[params.urls]
  demologin = "/demologin"
  app_project = "/app/#/projects"
  app_contracts = "/app/#/contracts"
  app_report = "/app/#/report"

[params]
  email = "<a href='mailto:support@kompound.solutions'>support@kompound.solutions</a>"
  phone = "<a href='tel:+491632662555'>+49 163 266 2555</a>"
  fax = "<a href='fax:+4932223942249'>+49 32223 942 249</a>"

# The site's parameters
[languages.de.params]
  dateFormat = "6. Januar 2006"
  cookiemsg = "Diese Webseite nutzt Cookies um Ihnen das beste Erlebnis auf dieser Seite zu ermöglichen"
  cookielearnmore = "Erfahren Sie mehr"
  cookieok = "Schließen"

[languages.en.params]
  dateFormat = "6 January 2006"
  cookiemsg = "This website uses cookies to ensure you get the best experience on our website."
  cookielearnmore = "Learn more"
  cookieok = "Dismiss"

  [languages.en.params.slider]
    title = "A digital marketing &amp; design agency"
    subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [languages.de.params.slider]
    title = "A digital marketing &amp; design agency"
    subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [languages.en.params.feature]
    title = "AWe believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [languages.en.params.feature.button]
      caption = "Go here"
      url = "#"

  [languages.de.params.feature]
    title = "AWe believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [languages.de.params.feature.button]
      caption = "Go here"
      url = "#"

  [languages.en.params.call]
    enable = true
    title = "We call you back"
    close = "Close"
    schedule = "Schedule callback"
    formname = "Company / Name"
    formtel = "Phone Number"
    formsubject = "(Optional) Subject"
    formtime = "Preferred time"
    formtoday = "Today"
    [languages.en.params.call.btnRequestQuote]
      msg = "Request an instant, no-obligation quote"
      caption = "Get a quote!"
      url = "/quote"
    [languages.en.params.call.btnContact]
      msg = "Request an instant, no-obligation quote"
      caption = "Contact us"
      url = "/contact"
    [languages.en.params.call.btnCallback]
      msg = "Enter your details and we call you back!"
      caption = "Let us call you back"
      url = "#"

  [languages.de.params.call]
    enable = true
    title = "Wir rufen zurück"
    close = "Schließen"
    schedule = "Rückruf planen"
    formname = "Firmenname / Name"
    formtel = "Telefonnummer"
    formsubject = "(Optional) Thema"
    formtime = "Wunschzeit"
    formtoday = "Heute"
    [languages.de.params.call.btnRequestQuote]
      msg = "Request an instant, no-obligation quote"
      caption = "Unverbindlicher Kostenrechner"
      url = "/quote"
    [languages.de.params.call.btnContact]
      msg = "Request an instant, no-obligation quote"
      caption = "Kontaktieren Sie uns"
      url = "/contact"
    [languages.de.params.call.btnCallback]
      msg = "Let us call you back!"
      caption = "Rückruf vereinbaren"
      url = "/contact"
